export const menuOptions = {
    Action: false,
    Adventure: false,
    Comedy: false,
    "Crime & Mystery": false,
    Fantasy: false,
    Historical: false,
    Horror: false,
    Romance: false,
    Satire: false,
    "Science Fiction": false,
    Speculative: false,
    Thriller: false,
    Isekai: false,
    Other: false,
}